version: '3.8'

services:
  app:
    build: .
    container_name: salesbuddy_backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    restart: always
    depends_on:
      - salesbuddy_db_container

  salesbuddy_db_container:
    image: postgres:15
    container_name: salesbuddy_db_container
    restart: always
    environment:
      # O Postgres usa nomes de variáveis específicos
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: