version: '3.8'

services:
  app:
    build: .
    container_name: salesbuddy_backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./database_data:/app/database
    environment:
      - NODE_ENV=development
      - JWT_SECRET=sua_chave_secreta
    restart: always

volumes:
  database_data: