version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: meu_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: process.env.DB_ROOT_PASSWORD || 'senha_segura'
      MYSQL_DATABASE: process.env.DB_NAME || 'meu_banco_de_dados'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: